- name: Setup Kubernetes and OpenShift
  hosts: labblocal
  become: true
  vars_files:
    - kube_vars.yml
    - grafana_vars.yml 
  
  tasks:

    - name: Setup Container Runtime #https://kubernetes.io/docs/setup/production-environment/container-runtimes/
      become: true
      tags: containernerd 
      block:
        - name: ContainerRuntime #Choices Containerd, CRI-O, Docker Engine, Mirantis  
          include_role:
            name: containerd  

    - name: Install Kubernetes
      become: true
      tags: kube
      block:
        - name: Install Kubernetes  
          include_role:
            name: kubernetes_install

#     - name: Install OpenShift and Kubernetes
#       become: true
#       tags: kube_shift
#       block:
#         - name: Install Kubernetes and Open Shift Packages 
#           include_role:
#             name: install_packages
 
    - name: Install Grafana 
      tags: grafana
      block:
        - name: Install grafana 
          include_role:
            name: grafana-install

    - name: Debug packages  
      tags: debug
      block:
        - name: Debug Packages
          include_role:
            name: debug_packages

